# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Privacy Guides
email: jonah@privacyguides.org
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.privacyguides.org" # the base hostname & protocol for your site, e.g. http://example.com
sass:
    sass_dir: _sass
excerpt_separator: <!--more-->
collections_dir: collections
collections:
  evergreen:
    output: true
    permalink: /:name/
  devices:
    output: true
    permalink: /devices/:path/
  software:
    output: true
    permalink: /software/:path/
  providers:
    output: true
    permalink: /providers/:path/
  posts:
    permalink: /blog/:year/:month/:day/:title/
  authors:
    permalink: /blog/authors/:path/

build:
     date:
     time:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-brotli
exclude: [privacytools.io/]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
