# Copyright (c) 2021-2025 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: ðŸ“¦ Immediate Releases

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "blog/**"
      - "videos/**"

concurrency:
  group: release-deployment
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  submodule:
    strategy:
      matrix:
        repo: [mkdocs-material-insiders, brand]
    uses: privacyguides/.github/.github/workflows/download-repo.yml@main
    with:
      repo: ${{ matrix.repo }}
    secrets:
      ACTIONS_SSH_KEY: ${{ secrets.ACTIONS_SSH_KEY }}

  build_blog:
    needs: submodule
    permissions:
      contents: read
    uses: ./.github/workflows/build-blog.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      continue-on-error: false
      context: production

  build_videos:
    needs: submodule
    permissions:
      contents: read
    uses: ./.github/workflows/build-videos.yml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      continue-on-error: false
      context: production

  deploy:
    needs: [build_blog, build_videos]
    uses: privacyguides/webserver/.github/workflows/deploy-garage.yml@main
    with:
      environment: production
    secrets:
      PROD_GARAGE_KEY_ID: ${{ secrets.PROD_GARAGE_KEY_ID }}
      PROD_GARAGE_SECRET_KEY: ${{ secrets.PROD_GARAGE_SECRET_KEY }}

  cleanup:
    if: ${{ always() }}
    needs: [build_blog, build_videos]
    uses: privacyguides/.github/.github/workflows/cleanup.yml@main
