# Copyright (c) 2021-2023 Jonah Aragon <jonah@triplebit.net>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: ðŸ“¦ Releases

on:
  push:
    tags:
      - '*'

jobs:
  production:
    name: Push release to production
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ssh-key: ${{ secrets.ACTIONS_SSH_KEY }}
          submodules: 'true'

      - name: Push to production branch
        run: |
          git push origin HEAD:production
  
  build:
    name: Create release packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ssh-key: ${{ secrets.ACTIONS_SSH_KEY }}
          submodules: 'true'
      
      - name: Pages setup
        uses: actions/configure-pages@v3

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Cache files
        uses: actions/cache@v3.3.1
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Python dependencies
        run: |
          pip install pipenv
          pipenv install
          sudo apt install pngquant

      - name: Build website
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARDS: false
        run: |
          pipenv run mkdocs build --config-file config/mkdocs-offline.yml
          pipenv run mkdocs --version
      
      - name: Package website
        run: |
          tar -czvf offline.tar.gz site
          zip -r -q offline.zip site

      - name: Upload tar.gz file
        uses: actions/upload-artifact@v3
        with:
          name: offline.tar.gz
          path: offline.tar.gz
      
      - name: Upload zip file
        uses: actions/upload-artifact@v3
        with:
          name: offline.zip
          path: offline.zip
      
      - name: Create ZIM File
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/openzim/zim-tools:3.1.3
          options: -v ${{ github.workspace }}:/data
          run: |
            zimwriterfs -w index.html -I assets/brand/PNG/Square/pg-yellow.png -l eng -t "Privacy Guides" -d "Your central privacy and security resource to protect yourself online." -c "Privacy Guides" -p "Jonah Aragon" -n "Privacy Guides" -e "https://github.com/privacyguides/privacyguides.org" /data/site /data/privacy_guides.zim
      
      - name: Upload ZIM file
        uses: actions/upload-artifact@v3
        with:
          name: privacy_guides.zim
          path: privacy_guides.zim

  release:
    name: Create release notes
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: offline.tar.gz

      - uses: actions/download-artifact@v3
        with:
          name: offline.zip

      - uses: actions/download-artifact@v3
        with:
          name: privacy_guides.zim

      - name: Create release notes
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          token: ${{ secrets.REPO_TOKEN }}
          artifacts: "offline.zip,offline.tar.gz,privacy_guides.zim"
