name: Code tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  deps:
    name: "Dependency Install"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm run assets:install

  build:
    name: "Jekyll Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Jekyll build
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-jekyll-${{ hashFiles('**/*.html') }}
        restore-keys: |
          ${{ runner.os }}-jekyll-
    - name: Build website
      uses: ./.github/actions/build

  link:
    name: "Broken Hyperlinks (Internal)"
    runs-on: ubuntu-latest
    needs: [deps, build]

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Cache Jekyll build
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-jekyll-${{ hashFiles('**/*.html') }}
        restore-keys: |
          ${{ runner.os }}-jekyll-
    - name: Build website
      uses: ./.github/actions/build
    - name: Copy built site to production
      run: |
        mv ${{ github.workspace }}/_site /tmp/
        mkdir -p /tmp/src
        mv ${{ github.workspace }}/* /tmp/src/
        mkdir -p ${{ github.workspace }}/src
        mv /tmp/src/* ${{ github.workspace }}/src/
        mv /tmp/_site ${{ github.workspace }}/
    - name: Internal link checker
      uses: untitaker/hyperlink@0.1.15
      with:
        args: _site/ --sources src/

  extlink:
    name: "Broken Hyperlinks (External)"
    runs-on: ubuntu-latest
    needs: [build, link]
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache Jekyll build
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/*.html') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - name: Build website
        uses: ./.github/actions/build
      - name: Cache HTMLProofer
        id: cache-htmlproofer
        uses: actions/cache@v2
        with:
          path: tmp/.htmlproofer
          key: ${{ runner.os }}-htmlproofer
      - name: Check All External Links (Informational)
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: ${{ github.workspace }}/_site
          arguments: --assume-extension --external_only --internal-domains privacyguides.org,www.privacyguides.org --timeframe 30d
        continue-on-error: true
      - name: Check External Links (Only 4XX)
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: ${{ github.workspace }}/_site
          arguments: --assume-extension --external_only --only_4xx --internal-domains privacyguides.org,www.privacyguides.org --timeframe 30d
        continue-on-error: true

  https:
    name: "Require HTTPS Internal Images"
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache Jekyll build
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/*.html') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - name: Build website
        uses: ./.github/actions/build
      - name: Check Images
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: ${{ github.workspace }}/_site
          arguments: --assume-extension --check-img-http --internal-domains privacyguides.org,www.privacyguides.org --disable-external --checks-to-ignore LinkCheck,ScriptCheck

  scripts:
    name: "Script Reference Checks"
    runs-on: ubuntu-latest
    needs: [build, link]
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache Jekyll build
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/*.html') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - name: Build website
        uses: ./.github/actions/build
      - name: Check HTML
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: ${{ github.workspace }}/_site
          arguments: --assume-extension --check-html --disable-external --check-sri --report-script-embeds --internal-domains privacyguides.org,www.privacyguides.org --checks-to-ignore LinkCheck,ImageCheck,HtmlCheck

  tags:
    name: "HTML Tag Test"
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache Jekyll build
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/*.html') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - name: Build website
        uses: ./.github/actions/build
      - name: Check HTML
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: ${{ github.workspace }}/_site
          arguments: --assume-extension --check-html --disable-external --allow-hash-href --internal-domains privacyguides.org,www.privacyguides.org --report-invalid-tags --report-eof-tags --report-mismatched-tags --checks-to-ignore LinkCheck,ImageCheck,ScriptCheck

  entity:
    name: "HTML Entity Names Test"
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache Jekyll build
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/*.html') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - name: Build website
        uses: ./.github/actions/build
      - name: Check HTML
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: ${{ github.workspace }}/_site
          arguments: --assume-extension --check-html --disable-external --allow-hash-href --internal-domains privacyguides.org,www.privacyguides.org --report-missing-names --checks-to-ignore LinkCheck,ImageCheck,ScriptCheck

  misc:
    name: "Misc HTML Test"
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache Jekyll build
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/*.html') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - name: Build website
        uses: ./.github/actions/build
      - name: Check HTML
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: ${{ github.workspace }}/_site
          arguments: --assume-extension --check-html --disable-external --internal-domains privacyguides.org,www.privacyguides.org --report-missing-doctype --checks-to-ignore LinkCheck,ImageCheck,ScriptCheck

  opengraph:
    name: "OpenGraph Test"
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache Jekyll build
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-jekyll-${{ hashFiles('**/*.html') }}
          restore-keys: |
            ${{ runner.os }}-jekyll-
      - name: Build website
        uses: ./.github/actions/build
      - name: Check HTML
        uses: chabad360/htmlproofer@v1.1
        with:
          directory: ${{ github.workspace }}/_site
          arguments: --assume-extension --disable-external --check-opengraph --checks-to-ignore LinkCheck,ImageCheck,ScriptCheck
